extends:
  - 'airbnb'

env:
  browser: true
  es6: true

parser: '@typescript-eslint/parser'

rules:
  import/extensions:
    - 0
    - 'ignorePackages'

plugins:
  - '@typescript-eslint'

root: true

settings:
  import/resolver:
    typescript: true
    node: true
